#!/usr/bin/env bash
# Runs pylint for Travis CI - run this from the projects root directory
# Why: https://fullvalence.com/2016/11/22/travis-and-pylint/

rc=$(pylint spacexlaunchbot --rcfile=.pylintrc)

# Fail Travis build if Pylint returns fatal (1) or error (2)
if [[ rc == 1 || rc == 2 ]]; then
    echo "pylint failed" && exit 1
else
    echo "pylint passed" && exit 0
fi
