#!/usr/bin/env bash

askyn() {
    while true; do
        read -p "$1 [Yy/Nn]" yn
        case $yn in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer y or n";;
        esac
    done
}

# https://stackoverflow.com/a/34143401/6396652
exists() {
  command -v "$1" >/dev/null 2>&1
}

cat << EndOfMsg

SpaceXLaunchBot Setup
---------------------

Dependencies to be installed:
- python3-venv from apt
- redis-server from apt
- pip3 from pypa (if not installed already)

Required:
- Discord bot API token
- Discord Bot List API token
- Bots on Discord API token

EndOfMsg

askyn "Is this correct?" || exit

exists python3 || (echo "python3 does not exist, cannot continue" && exit)

cd /opt/SpaceXLaunchBot || (echo "/opt/SpaceXLaunchBot does not exist, cannot continue" && exit)

echo "Installing apt dependencies"
sudo apt install python3-venv redis-server -y

# pip is not actually required to make the venv, but installing this means that:
# - There is no confusion between system-wide pip and the pip that's copied to the venv
# - The default packages (setuptools, wheel) are installed correctly
if ! exists pip3; then
    echo "Installing the latest version of pip for python3"
    curl https://bootstrap.pypa.io/get-pip.py | sudo python3
fi

echo "Setting up slb-venv"
sudo python3 -m venv slb-venv
echo "Installing requirements inside slb-venv"
sudo slb-venv/bin/pip3 install -r requirements.txt

echo "Setting up spacexlaunchbot user and fs permissions"
sudo adduser --system --group --no-create-home spacexlaunchbot
sudo chown -R spacexlaunchbot:spacexlaunchbot /opt/SpaceXLaunchBot
# Permissions Explanation
# Capital X --> https://www.g-loaded.eu/2005/11/08/the-use-of-the-uppercase-x-in-chmod/
# Give owner of the file (spacexlaunchbot) the ability to r, w, and X all files
# Allow everyone else to r and X, don't allow anyone else to w
sudo chmod -R u+rwX,go+rX,go-w /opt/SpaceXLaunchBot

echo "Setting up /var/log/spacexlaunchbot"
sudo mkdir /var/log/spacexlaunchbot
sudo chown spacexlaunchbot:spacexlaunchbot /var/log/spacexlaunchbot

echo "Copying over systemd file(s)"
sudo cp -R -p services/systemd/. /etc/systemd/system

echo "Copying redis config to /etc/redis"
# The apt installed version of redis-server looks for a config file here by default
sudo cp -R services/redis/. /etc/redis
echo "Restarting Redis"
sudo systemctl restart redis

if askyn "Edit spacexlaunchbot.service now? This will have to be done before running it";
then sudo nano /etc/systemd/system/spacexlaunchbot.service; fi

cat << EndOfMsg

Setup Finished
--------------
To start spacexlaunchbot, enable and start it using systemctl
To use a previous Redis dump, stop redis, move the dump to /var/lib/redis and then start redis

EndOfMsg

# To get a copy of dump.rdb:
# sudo cp /var/lib/redis/dump.rdb ~/ && sudo chown USERNAME dump.rdb
# Then download dump.rdb from ~/
