@"
POSTGRES_PASSWORD=$Env:POSTGRES_PASSWORD
SLB_API_TOKEN_DISCORD=$Env:SLB_API_TOKEN_DISCORD
DISCORD_OAUTH_CLIENT_SECRET=$Env:DISCORD_OAUTH_CLIENT_SECRET
SLB_API_TOKEN_BOT_LIST_DBL=$Env:SLB_API_TOKEN_BOT_LIST_DBL
SLB_API_TOKEN_BOT_LIST_BOD=$Env:SLB_API_TOKEN_BOT_LIST_BOD
SLB_API_TOKEN_BOT_LIST_DBG=$Env:SLB_API_TOKEN_BOT_LIST_DBG
SLB_API_TOKEN_BOT_LIST_BFD=$Env:SLB_API_TOKEN_BOT_LIST_BFD
SLB_DB_HOST=$Env:SLB_DB_HOST
DISCORD_OAUTH_CLIENT_ID=$Env:DISCORD_OAUTH_CLIENT_ID
POSTGRES_USER=$Env:POSTGRES_USER
POSTGRES_DB=$Env:POSTGRES_DB
"@ | Out-File .env -Encoding utf8 -NoNewline
